version: '3.8'

services:
  blog_db:
    image: postgres:16
    container_name: blog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: blogdb
    ports:
      - "5431:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d


  backend:
    build: ./backend
    container_name: blog_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      DB_HOST: blog_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: blogdb
    depends_on:
      - blog_db

  frontend:
    build: ./frontend
    container_name: blog_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5001
    depends_on:
      - backend


volumes:
  blog_data:
